package projetator;

public enum Role {
    GRADUANDO, MESTRANDO, DOUTORANDO, PROFESSOR, PESQUISADOR,
    PROFISSIONAL_TESTADOR, PROFISSIONAL_DESENVOLVEDOR,
    PROFISSIONAL_ANALISTA, TECNICO, NAO_ESPECIFICADO
}
